{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "postgres-filebeat.clusterRoleBindingName" . }} # filebeat-cluster-role-binding
  labels:
    app.kubernetes.io/name: {{ template "postgres-filebeat.name" . }}
    helm.sh/chart: {{ template "postgres-filebeat.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "postgres-filebeat.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "postgres-filebeat.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }} # elastic-stack
{{ end }}