{{- if eq .Values.configTarget "ConfigMap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgres-filebeat.config" . }}
  labels:
    app.kubernetes.io/name: {{ template "postgres-filebeat.name" . }}
    helm.sh/chart: {{ template "postgres-filebeat.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: elk-filebeat
  namespace: elastic-stack
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/postgresql/*.log
      processors:
      - add_kubernetes_metadata:
          in_cluster: true
    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
{{- end }}