{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "postgres-filebeat.pvcName" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: standard
{{- end }}